version: '3.8'
services: 
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=video_db
    container_name: postgres-db-nestjs
    volumes:
      - postgres:/var/lib/postgresql/data 
    ports:
      - '5432:5432'

volumes:
  postgres:

